server:
  port: 29100

spring:
  application:
    name: newbee-gateway-admin

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

    # 网关开启服务注册与服务发现
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://user-service
          order: 1
          predicates:
            - Path=/users/admin/**

  redis:
    database: 0
    host: localhost
    port: 6379
    password: notsosecure
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
